use std::collections::{HashMap, HashSet};

use crate::models::{
    CriticalType,
    GameState,
    GameStatus,
    Hex,
    HexId,
    MusicTrackId,
    Outcome,
    RollResult,
    TurnPhase,
    TurnState,
};

pub const PLAYER_COLORS: &[&str] = &[
    "#e74c3c",
    "#3498db",
    "#2ecc71",
    "#f39c12",
    "#1abc9c",
    "#e67e22",
    "#f1c40f",
    "#ff6b6b",
];

pub const MAX_HEAT: i32 = 5;
pub const STARTING_HOPE: i32 = 10;
pub const DEFAULT_HEX_COUNT: usize = 14;
pub const MAX_BONUS: i32 = 8;

pub const NEIGHBOR_DIRECTIONS: [(i32, i32); 6] = [
    (1, 0),
    (1, -1),
    (0, -1),
    (-1, 0),
    (-1, 1),
    (0, 1),
];

/// Create the canonical ID used by both the server and client.
pub fn hex_id(q: i32, r: i32) -> HexId {
    format!("{q},{r}")
}

/// Parse a canonical hex ID.
///
/// This mirrors the client's parseHexId().
pub fn parse_hex_id(id: &str) -> Option<(i32, i32)> {
    let mut parts = id.split(',');

    let q = parts.next()?.parse::<i32>().ok()?;
    let r = parts.next()?.parse::<i32>().ok()?;

    // Reject IDs with more than two components.
    if parts.next().is_some() {
        return None;
    }

    Some((q, r))
}

/// Generate the same board as the TypeScript generateHexes().
///
/// The board is generated by hex distance from the origin, then
/// by q, then by r.
pub fn generate_hexes(count: usize) -> Vec<Hex> {
    let mut all: Vec<(i32, i32, i32)> = Vec::new();

    let max_r = (count as f64).sqrt().ceil() as i32 + 1;

    for r in -max_r..=max_r {
        for q in -max_r..=max_r {
            let s = -q - r;

            let dist = q.abs().max(r.abs()).max(s.abs());

            if dist <= max_r {
                all.push((q, r, dist));
            }
        }
    }

    /*
     * TypeScript:
     *
     * all.sort((a, b) =>
     *   a.dist - b.dist ||
     *   a.q - b.q ||
     *   a.r - b.r
     * )
     *
     * Rust's sort_by gives us the same ordering.
     */
    all.sort_by(|a, b| {
        a.2.cmp(&b.2)
            .then_with(|| a.0.cmp(&b.0))
            .then_with(|| a.1.cmp(&b.1))
    });

    all.into_iter()
        .take(count)
        .map(|(q, r, _)| Hex {
            id: hex_id(q, r),
            q,
            r,
            heat: 0,
            inscription: String::new(),
        })
        .collect()
}

/// Calculate axial hex distance.
pub fn hex_distance(a: &Hex, b: &Hex) -> i32 {
    let dq = a.q - b.q;
    let dr = a.r - b.r;
    let ds = -dq - dr;

    (dq.abs() + dr.abs() + ds.abs()) / 2
}

/// Return whether two hexes are adjacent.
pub fn are_neighbors(a: &Hex, b: &Hex) -> bool {
    hex_distance(a, b) == 1
}

/// Cost of selecting a bonus.
///
/// This mirrors:
///
/// bonus * bonus
pub fn bonus_cost(bonus: i32) -> i32 {
    bonus * bonus
}

/// Calculate the modifier applied to a roll.
///
/// This mirrors:
///
/// Math.min(bonus - heat, 3)
pub fn calculate_modifier(bonus: i32, heat: i32) -> i32 {
    (bonus - heat).min(3)
}

fn categorize_total(total: i32) -> Outcome {
    if total <= 5 {
        Outcome::Failure
    } else if total <= 8 {
        Outcome::Mixed
    } else {
        Outcome::Success
    }
}

/// Calculate the complete result of one roll.
///
/// This is a direct translation of calculateOutcome().
pub fn calculate_outcome(
    d1: u8,
    d2: u8,
    bonus: i32,
    heat: i32,
) -> RollResult {
    let modifier = calculate_modifier(bonus, heat);

    let total = d1 as i32 + d2 as i32 + modifier;

    let is_doubles = d1 == d2;

    let (outcome, critical) = if is_doubles && d1 <= 2 {
        (
            Outcome::Failure,
            Some(CriticalType::CriticalFailure),
        )
    } else if is_doubles && d1 <= 4 {
        if total <= 5 {
            (
                Outcome::Mixed,
                Some(CriticalType::Upgrade),
            )
        } else {
            (categorize_total(total), None)
        }
    } else if is_doubles && d1 >= 5 {
        (
            Outcome::Success,
            Some(CriticalType::CriticalSuccess),
        )
    } else {
        (categorize_total(total), None)
    };

    RollResult {
        d1,
        d2,
        bonus,
        heat,
        modifier,
        total,
        outcome,
        critical,
    }
}

/// Calculate hope gained when a turn ends.
///
/// This is a direct translation of calculateHopeGained().
pub fn calculate_hope_gained(
    outcome: Outcome,
    chain_heat_sum: i32,
) -> i32 {
    match outcome {
        Outcome::Success => {
            4 + 2 * chain_heat_sum * chain_heat_sum
        }

        Outcome::Mixed => {
            4 + chain_heat_sum * chain_heat_sum
        }

        Outcome::Failure => 4,
    }
}

/// Generate the initial game state.
pub fn default_game_state() -> GameState {
    let hexes_vec = generate_hexes(DEFAULT_HEX_COUNT);

    let mut hexes = HashMap::new();
    let mut hex_order = Vec::with_capacity(hexes_vec.len());

    for hex in hexes_vec {
        hex_order.push(hex.id.clone());
        hexes.insert(hex.id.clone(), hex);
    }

    GameState {
        status: GameStatus::Setup,
        hexes,
        hex_order,
        players: HashMap::new(),

        turn: TurnState {
            phase: TurnPhase::Idle,
            active_player_id: None,
            bonus: 0,
            chain: Vec::new(),
            rolls: Vec::new(),
            final_outcome: None,
            heat_snapshot: HashMap::new(),
        },

        music_track: MusicTrackId::None,
    }
}

/// Return all currently occupied hex IDs.
pub fn occupied_positions(
    players: impl Iterator<Item = impl std::borrow::Borrow<crate::models::Player>>,
) -> HashSet<HexId> {
    players
        .filter_map(|player| player.borrow().position.clone())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_state_uses_correct_constants() {
        let state = default_game_state();

        assert_eq!(state.hexes.len(), 14);
        assert_eq!(state.hex_order.len(), 14);
    }

    #[test]
    fn hex_ids_match_client_format() {
        assert_eq!(hex_id(0, 0), "0,0");
        assert_eq!(hex_id(1, -1), "1,-1");
        assert_eq!(hex_id(-3, 7), "-3,7");
    }

    #[test]
    fn hex_ids_can_be_parsed() {
        assert_eq!(parse_hex_id("3,-2"), Some((3, -2)));
        assert_eq!(parse_hex_id("-4,7"), Some((-4, 7)));
        assert_eq!(parse_hex_id("invalid"), None);
        assert_eq!(parse_hex_id("1,2,3"), None);
    }

    #[test]
    fn center_hex_is_first() {
        let hexes = generate_hexes(DEFAULT_HEX_COUNT);

        assert_eq!(hexes[0].q, 0);
        assert_eq!(hexes[0].r, 0);
        assert_eq!(hexes[0].id, "0,0");
    }

    #[test]
    fn generated_hex_ids_are_unique() {
        let hexes = generate_hexes(DEFAULT_HEX_COUNT);

        let ids: HashSet<_> =
            hexes.iter().map(|h| h.id.clone()).collect();

        assert_eq!(ids.len(), hexes.len());
    }

    #[test]
    fn neighboring_hexes_have_distance_one() {
        let a = Hex {
            id: hex_id(0, 0),
            q: 0,
            r: 0,
            heat: 0,
            inscription: String::new(),
        };

        let b = Hex {
            id: hex_id(1, 0),
            q: 1,
            r: 0,
            heat: 0,
            inscription: String::new(),
        };

        assert_eq!(hex_distance(&a, &b), 1);
        assert!(are_neighbors(&a, &b));
    }

    #[test]
    fn distant_hexes_are_not_neighbors() {
        let a = Hex {
            id: hex_id(0, 0),
            q: 0,
            r: 0,
            heat: 0,
            inscription: String::new(),
        };

        let b = Hex {
            id: hex_id(2, 0),
            q: 2,
            r: 0,
            heat: 0,
            inscription: String::new(),
        };

        assert_eq!(hex_distance(&a, &b), 2);
        assert!(!are_neighbors(&a, &b));
    }

    #[test]
    fn bonus_cost_is_squared() {
        assert_eq!(bonus_cost(0), 0);
        assert_eq!(bonus_cost(1), 1);
        assert_eq!(bonus_cost(2), 4);
        assert_eq!(bonus_cost(3), 9);
        assert_eq!(bonus_cost(8), 64);
    }

    #[test]
    fn modifier_matches_client_logic() {
        assert_eq!(calculate_modifier(3, 0), 3);
        assert_eq!(calculate_modifier(8, 5), 3);
        assert_eq!(calculate_modifier(2, 0), 2);
        assert_eq!(calculate_modifier(2, 3), -1);
        assert_eq!(calculate_modifier(0, 5), -5);
    }

    #[test]
    fn total_categories_match_client_logic() {
        assert_eq!(
            categorize_total(5),
            Outcome::Failure
        );

        assert_eq!(
            categorize_total(6),
            Outcome::Mixed
        );

        assert_eq!(
            categorize_total(8),
            Outcome::Mixed
        );

        assert_eq!(
            categorize_total(9),
            Outcome::Success
        );
    }

    #[test]
    fn critical_failure_is_detected() {
        let result = calculate_outcome(1, 1, 0, 0);

        assert_eq!(result.outcome, Outcome::Failure);
        assert_eq!(
            result.critical,
            Some(CriticalType::CriticalFailure)
        );
    }

    #[test]
    fn critical_success_is_detected() {
        let result = calculate_outcome(5, 5, 0, 0);

        assert_eq!(result.outcome, Outcome::Success);
        assert_eq!(
            result.critical,
            Some(CriticalType::CriticalSuccess)
        );
    }

    #[test]
    fn upgrade_is_detected() {
        /*
         * 3 + 3 = 6 normally gives mixed.
         *
         * To trigger the special branch we need total <= 5.
         * Heat can make that happen.
         */
        let result = calculate_outcome(3, 3, 0, 2);

        assert_eq!(result.total, 4);
        assert_eq!(result.outcome, Outcome::Mixed);
        assert_eq!(
            result.critical,
            Some(CriticalType::Upgrade)
        );
    }

    #[test]
    fn hope_calculation_matches_client_logic() {
        assert_eq!(
            calculate_hope_gained(Outcome::Failure, 10),
            4
        );

        assert_eq!(
            calculate_hope_gained(Outcome::Mixed, 2),
            8
        );

        assert_eq!(
            calculate_hope_gained(Outcome::Success, 2),
            12
        );
    }
}